---
# tasks file for ansible-role-openscap
- name: install openscap scanner
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openscap-scanner
    - scap-security-guide
- name: Set SSG content base path
  set_fact:
    ssg_base: /usr/share/xml/scap/ssg/content

- name: run openscap scan ospp profile
  command: oscap xccdf eval \
    --profile xccdf_org.ssgproject.content_profile_ospp \
    --results {{ openscap_datadir }}/scan.xml \
    --report {{ openscap_datadir }}/scan-report.html \
    {{ ssg_base }}/ssg-rhel{{ ansible_distribution_major_version }}-ds.xml
  ignore_errors: yes

- name: remediate system
  command: oscap xccdf eval \
    --remediate \
    --profile xccdf_org.ssgproject.content_profile_{{ openscap_oscap_profile }} \
    --results {{ openscap_datadir }}/scan.xml \
    {{ ssg_base }}/ssg-rhel{{ ansible_distribution_major_version }}-ds.xml
  when: openscap_remediate
  ignore_errors: yes

- name: upload scap report to Red Hat Cloud Management Services
  command: insights-client \
    --verbose \
    --payload {{ openscap_datadir }}/scan.xml \
    --content-type application/vnd.redhat.compliance.something+tgz
  when: openscap_upload
